var = {"clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_0": ['nan nan', 'nan'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_1": [
           'целеустремленность коммуникабельность', 'дипломированный психотерапевт', 'вакцинированы коронаваком',
           'невропатологи фтизиотерапевты', 'вакцинирвоанных украинцев'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_2": ['parla italiano', 'italiano',
                                                                                         'chi parla', 'parla', 'chi'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_3": ['grazie buongiorno',
                                                                                         'gabriela grazie',
                                                                                         'ucraina gabriela',
                                                                                         'ciao sono', 'sono din'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_4": ['amazon se', 'amazon', 'se'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_5": ['sanpaolo bank', 'bank',
                                                                                         'intesa sanpaolo', 'intesa',
                                                                                         'sanpaolo'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_6": ['fake informations',
                                                                                         'bruh fake', 'fake',
                                                                                         'informations', 'bruh'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_7": ['dichiarazione di',
                                                                                         'dichiarazione',
                                                                                         'di ospitalità', 'ospitalità',
                                                                                         'di'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_8": ['ria'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_9": ['bozen регион', 'регион',
                                                                                         'provinz bozen', 'provinz',
                                                                                         'bozen'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_10": [],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_11": ['trenit'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_12": ['100'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_13": ['lido jesolo', 'jesolo',
                                                                                          'lido'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_14": ['subito idealista',
                                                                                          'idealista', 'subito'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_15": ['ukraina centr', 'ukraina',
                                                                                          'centr'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_16": ['arivatte italia',
                                                                                          'italia cerci', 'italia',
                                                                                          'sono arivatte',
                                                                                          'apulien sono'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_17": ['qualcuno puglia',
                                                                                          'puó contattarmi',
                                                                                          'puó contattare',
                                                                                          'giorni aumentano',
                                                                                          'direttamente interessato'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_18": ['qualcuno puglia', 'qualcuno',
                                                                                          'puglia'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_19": ['solo roma', 'roma solo',
                                                                                          'solo merano', 'merano',
                                                                                          'roma'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_20": ['febbraio 2022',
                                                                                          '2022 apolidi',
                                                                                          '2022 modalità', 'marzo 2023',
                                                                                          '2022 tali'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_21": ['snejka'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_22": [],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_23": ['scrivi privato',
                                                                                          'okay scrivi', 'scrivi',
                                                                                          'privato', 'okay'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_24": ['48'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_0": ['nan nan', 'nan'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_1": [
           'ukrainerussieupdates fighting', 'ukrainians invincible', 'ukrainian marines',
           'ukrainerussieupdates battles', 'fighting ukraine'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_2": ['kramatorsk'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_3": ['boy jewish', 'jewish',
                                                                                             'dee boy', 'boy', 'dee'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_4": ['satellite photo',
                                                                                             'satellite',
                                                                                             'photo mariupol',
                                                                                             'maxar technologies',
                                                                                             'mariupol maxar'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_5": ['paula bronstein',
                                                                                             'borodianka photo',
                                                                                             'photo paula', 'paula',
                                                                                             'borodianka'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_6": ['realhasidicmedia'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_7": ['mariupol today', 'today',
                                                                                             'mariupol'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_8": ['dance ukraine',
                                                                                             'london coliseum', 'dance',
                                                                                             'ukraine london',
                                                                                             'coliseum elliott'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_9": ['coincidence'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_10": ['economist magazine',
                                                                                              'cover economist',
                                                                                              'economist', 'magazine',
                                                                                              'new cover'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_11": ['marching maple',
                                                                                              'ukrainians marching',
                                                                                              'maple avenue',
                                                                                              'marching', 'maple'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_12": ['15m bunker', 'bunker',
                                                                                              '15m'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_13": ['100 100', '100'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_14": ['cool'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_15": ['double triple', 'triple',
                                                                                              'double'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_16": ['true'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_17": [
           'a5ac6f8ced7c4f228bca23fc13fb1ccb share_bandit_exp', 'utm_term a5ac6f8ced7c4f228bca23fc13fb1ccb',
           'a5ac6f8ced7c4f228bca23fc13fb1ccb', '963a136d7d46 utm_source', 'ba00 963a136d7d46'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_18": ['live live', 'live'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_0": ['nan nan', 'nan'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_1": [
           'целеустремленность коммуникабельность', 'дипломированный психотерапевт', 'вакцинированы коронаваком',
           'невропатологи фтизиотерапевты', 'вакцинирвоанных украинцев'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_2": ['parla italiano', 'italiano',
                                                                                         'chi parla', 'parla', 'chi'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_3": ['grazie buongiorno',
                                                                                         'gabriela grazie',
                                                                                         'ucraina gabriela',
                                                                                         'ciao sono', 'sono din'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_4": ['amazon se', 'amazon', 'se'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_5": ['sanpaolo bank', 'bank',
                                                                                         'intesa sanpaolo', 'intesa',
                                                                                         'sanpaolo'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_6": ['fake informations',
                                                                                         'bruh fake', 'fake',
                                                                                         'informations', 'bruh'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_7": ['dichiarazione di',
                                                                                         'dichiarazione',
                                                                                         'di ospitalità', 'ospitalità',
                                                                                         'di'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_8": ['ria'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_9": ['bozen регион', 'регион',
                                                                                         'provinz bozen', 'provinz',
                                                                                         'bozen'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_10": [],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_11": ['trenit'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_12": ['100'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_13": ['lido jesolo', 'jesolo',
                                                                                          'lido'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_14": ['subito idealista',
                                                                                          'idealista', 'subito'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_15": ['ukraina centr', 'ukraina',
                                                                                          'centr'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_16": ['arivatte italia',
                                                                                          'italia cerci', 'italia',
                                                                                          'sono arivatte',
                                                                                          'apulien sono'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_17": ['qualcuno puglia',
                                                                                          'puó contattarmi',
                                                                                          'puó contattare',
                                                                                          'giorni aumentano',
                                                                                          'direttamente interessato'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_18": ['qualcuno puglia', 'qualcuno',
                                                                                          'puglia'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_19": ['solo roma', 'roma solo',
                                                                                          'solo merano', 'merano',
                                                                                          'roma'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_20": ['febbraio 2022',
                                                                                          '2022 apolidi',
                                                                                          '2022 modalità', 'marzo 2023',
                                                                                          '2022 tali'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_21": ['snejka'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_22": [],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_23": ['scrivi privato',
                                                                                          'okay scrivi', 'scrivi',
                                                                                          'privato', 'okay'],
       "clustering_output\Channel-Ukraineitaly2021_channel_messages_cleaned/cluster_24": ['48'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_0": ['nan nan', 'nan'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_1": [
           'ukrainerussieupdates fighting', 'ukrainians invincible', 'ukrainian marines',
           'ukrainerussieupdates battles', 'fighting ukraine'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_2": ['kramatorsk'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_3": ['boy jewish', 'jewish',
                                                                                             'dee boy', 'boy', 'dee'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_4": ['satellite photo',
                                                                                             'satellite',
                                                                                             'photo mariupol',
                                                                                             'maxar technologies',
                                                                                             'mariupol maxar'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_5": ['paula bronstein',
                                                                                             'borodianka photo',
                                                                                             'photo paula', 'paula',
                                                                                             'borodianka'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_6": ['realhasidicmedia'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_7": ['mariupol today', 'today',
                                                                                             'mariupol'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_8": ['dance ukraine',
                                                                                             'london coliseum', 'dance',
                                                                                             'ukraine london',
                                                                                             'coliseum elliott'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_9": ['coincidence'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_10": ['economist magazine',
                                                                                              'cover economist',
                                                                                              'economist', 'magazine',
                                                                                              'new cover'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_11": ['marching maple',
                                                                                              'ukrainians marching',
                                                                                              'maple avenue',
                                                                                              'marching', 'maple'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_12": ['15m bunker', 'bunker',
                                                                                              '15m'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_13": ['100 100', '100'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_14": ['cool'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_15": ['double triple', 'triple',
                                                                                              'double'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_16": ['true'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_17": [
           'a5ac6f8ced7c4f228bca23fc13fb1ccb share_bandit_exp', 'utm_term a5ac6f8ced7c4f228bca23fc13fb1ccb',
           'a5ac6f8ced7c4f228bca23fc13fb1ccb', '963a136d7d46 utm_source', 'ba00 963a136d7d46'],
       "clustering_output\Channel-ukrainerussieupdates_channel_messages_cleaned/cluster_18": ['live live', 'live'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_0": ['long live', 'long', 'live'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_1": [
           'https war_russia_tresh_smert_suicide', 'war_russia_tresh_smert_suicide',
           'war_russia_tresh_smert_suicide канал', 'flash_update_ukraine_war forpeace', 'invasion ukraine_4319525'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_2": ['bless emanuel',
                                                                                           'emanuel christ',
                                                                                           'jesus aman', 'christ jesus',
                                                                                           'jesus'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_3": ['nan nan', 'nan'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_4": ['hi hi', 'hi'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_5": ['hey'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_6": ['lies tell', 'lies',
                                                                                           'tell ya', 'tell', 'ya'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_7": [],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_8": ['greetings'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_9": ['putin right', 'putin',
                                                                                           'right'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_10": ['putin lover',
                                                                                            'telegram putin', 'putin',
                                                                                            'lover ramzan',
                                                                                            'got telegram'],
       "clustering_output\Channel-UkraineWarHelp24x7_channel_messages_cleaned/cluster_11": ['omg'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_0": ['nan nan', 'nan'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_1": [
           'i189234 angry_villagers_troops_block_us_military_convoy_from_advancing_in_syria',
           '99s_bids_pose_serious_threats_to_our_national_security_iraqi_legislator_says angry', 'arrogant zombie',
           '80 99s_bids_pose_serious_threats_to_our_national_security_iraqi_legislator_says',
           'angry_villagers_troops_block_us_military_convoy_from_advancing_in_syria'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_2": ['titanium'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_3": ['hi hi', 'hi'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_4": ['russian vietnam',
                                                                                               'shot russian',
                                                                                               'vietnam', 'russian',
                                                                                               'haha shot'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_5": ['vs t90', 't90',
                                                                                               'abrams vs', 'abrams',
                                                                                               'vs'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_6": ['windmills fight',
                                                                                               'fight', 'lol windmills',
                                                                                               'windmills', 'lol'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_7": ['cosmomino la',
                                                                                               '000 euro', 'euro 000',
                                                                                               'violenza 581',
                                                                                               '581 minaccia'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_8": [
           'miracolimilano miracoli_a_milano', 'miracoli_a_milano', 'milano miracolimilano', 'miracolo milano',
           'milano'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_9": ['1992 2022', '2022 pdf',
                                                                                               '11novembre2022 8p',
                                                                                               'fare 11novembre2022',
                                                                                               '11novembre2022'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_10": ['european thieves',
                                                                                                'thieves',
                                                                                                'modern european',
                                                                                                'european', 'modern'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_11": ['scum scum', 'scum'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_12": ['busy meeting',
                                                                                                'busy busy',
                                                                                                'meeting meeting',
                                                                                                'busy', 'meeting'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_13": ['difficulties',
                                                                                                'difficulties difficulties'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_14": ['horrible bastards',
                                                                                                'bastards bastards',
                                                                                                'horrible', 'bastards'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_15": ['bdsm bdsm', 'bdsm'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_16": ['500'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_17": ['north korea', 'korea',
                                                                                                'north'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_18": [
           'italian video_languages', 'hashtag italian', 'dell organizzazione', 'organizzazione lungo', 'italian'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_19": ['admin'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_20": ['baltic countries',
                                                                                                'baltic', 'countries'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_21": ['cars'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_22": ['navy seals', 'seals',
                                                                                                'navy'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_23": ['referenda'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_24": ['db'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_25": ['diretta 20',
                                                                                                '20 minuti',
                                                                                                'donetsk diretta',
                                                                                                'nato 155mm',
                                                                                                'autobus morti'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_26": ['bandera club',
                                                                                                'tel aviv', 'club tel',
                                                                                                'club', 'bandera'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_27": ['text'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_28": ['10 42', '17 06',
                                                                                                '22 10', '06 22', '42'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_29": ['danas'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_30": ['max maximum',
                                                                                                'maximum', 'max'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_31": ['merci merci', 'merci'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_32": [],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_33": ['grazie opuscolo',
                                                                                                'lingua italiana',
                                                                                                'opuscolo lingua',
                                                                                                'italiana', 'grazie'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_34": ['cowards action',
                                                                                                'cowards', 'action'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_35": ['texas bentley',
                                                                                                'russell texas',
                                                                                                'texas', 'bentley',
                                                                                                'russell'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_36": ['nonsense gossips',
                                                                                                'gossips rumores',
                                                                                                'rumores photoshop',
                                                                                                'gossips', 'photoshop'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_37": ['advertising really',
                                                                                                'advertising',
                                                                                                'really'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_38": ['hearsay'],
       "clustering_output\Channel-WARCRIMESINUKRAINEchat_channel_messages_cleaned/cluster_39": ['savages'],

       }
